name: Update Release Version

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version that should be released'
        required: true
        default: '1.2.3'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Get Latest Tag
        id: vars
        uses: WyriHaximus/github-action-get-previous-tag@v1
      # When executed by a release, checkout checks out the tag, not head
      - name: Switch to HEAD
        run: |
          env
          git branch
          git checkout HEAD
          git branch
      - run: |
          echo '${{ steps.vars.outputs.tag }}' > VERSION
      # Commit changes
      - name: Commit VERSION file
        run: |
          echo 'VERSION is ${{ steps.vars.outputs.tag }}'
          git add VERSION
          git config --global user.email "tools@mondoo.com"
          git config --global user.name "Mondoo Tools"
          git commit -m 'Update VERSION to ${{ steps.vars.outputs.tag }}'
          git push origin master -f
